name: 'Build and publish a DNAnexus applet'
description: 'Build & publish a DNAnexus applet to a specified project'
author: 'kurt.mueller@osumc.edu'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  project-id:
    description: 'The dnanexus project id in which to build/publish the app'
    required: true
  overwrite:
    description: 'Specify if the existing applet(s) of hte same name in the destination folder will be overwritten'
    required: true
    default: 'false'
  applet-directory:
    description: 'The directory in the repo that contains the dnanexus applet'
    required: true
    default: '.'
outputs:
  applet-id:
    description: "The id of the published DNAnexus applet"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-id }}
    - ${{ inputs.overwrite }}
    - ${{ inputs.applet-directory }}
